site_name: trajectory infrastructure upgrade
site_description: last update 11.04.2017

pages:
    - Home: index.md
    - Fundamentals: fundamentals.md
    - Paradigms: paradigms.md
    - Correspondence: correspondence.md
theme: readthedocs
markdown_extensions:
    - pymdownx.github
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

